name: Deploy Functions
description: This workflow deploys the Google Cloud Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Google Cloud Functions
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v2.1.7'
      with:
        project_id: ${{ secrets.CAPY_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.CAPY_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.CAPY_SERVICE_ACCOUNT }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install google-adk CLI
      run: pip install --upgrade pip google-adk

    - name: Run script file
      run: |
         chmod +x ./scripts/deploy_adk_cloud_run.sh
         ./scripts/deploy_adk_cloud_run.sh
      env:
        CAPY_PROJECT_ID: ${{ secrets.CAPY_PROJECT_ID }}
        CAPY_SERVER_REGION: ${{ secrets.CAPY_SERVER_REGION }}
      shell: bash